### ISSUE TITLE
Crash/Assertion when connecting mismatching protocol version to daemon

### ISSUE THREAD

**Issue by TheDraguun** [GENIVI/ramses#12]
Daemon from this Repo crashes in TCPConnectionSystem.cpp:1148 (assert(!m_platformSocketMap.contains(&socket));) when connecting the Renderer bundled with Ramses Studio 1.2.9. (Version: 13.0.0) or from SDK 17 (Version 17.0.1) on localhost, Win10.

Ramses Studio 1.2.9 / Ramses 13.0.0 / Protocol Version 184550400
Ramses SDK 17 / Ramses 17.0.1 / Protocol Version 56
Genivi Ramses / Ramses 0.0.0 / Protocol Version 73

**Comment by GENIVI-Ramses** [comment]
Hello TheDraguun,

Ramses Studio is not an open source project. But even if it was, version 1.2.9 is very old - it would definitely NOT work with the latest version of RAMSES.

Sorry to disappoint you but we can't make it work with your version of Ramses Studio... wherever you got it from ;) If you are interested in a tooling platform based on RAMSES, I would like to invite you to check the ideas we have been discussing with the Qt Company, and maybe join the discussions in the Genivi Graphics sharing group:
Link to Wiki Page describing the currently discussed ideas:
https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=31457568
Link to join the weekly Zoom call:
https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=16024743

**Comment by GENIVI-Ramses** [comment]
Hi TheDragoon,
no worries, BMW will not sue you for mentioning Ramses Studio ;))
I would also have liked to have it open sourced, but it is just not usable outside the context of BMW.
The version checking is intended - it prevents crashes from using binary incompatible versions of RAMSES. I suggest to address the issue offline since it is not related to RAMSES directly. Do you have our  contact @BMW?

**Comment by TheDraguun** [comment]
Hi there,
obviously the version checking is intended - e.g. the scenemanagers of ramses versions 13 and 17 tell me in the log output about the incompatible versions. The daemon (= scenemanager?) of this repo crashes instead of giving log output. My debugger says that it crashes due to an assertion in  TCPConnectionSystem.cpp:1148 (assert(!m_platformSocketMap.contains(&socket));). 
I have already triggered my contact to get an updated version of Ramses Studio - will use the demo clients for now.

**Comment by GENIVI-Ramses** [comment]
This is a known issue in the TCP communication system. There is a new update coming out soon which hopefully doesn't have the issue!
