### ISSUE TITLE
endline fixed

### ISSUE THREAD

**Issue by kwangjo** [GENIVI/ramses#15]
use Code : commit 4a40bfe18c6dba2aad5b15b760e345284e0df44d

environment : Ubuntu Desktop 16.04  not use Weston

Source Code Build Error fixed
 
Composite/ramses/renderer/Platform/WaylandUtilities/src/WaylandUtilities.cpp:110:9: error: expected ‘;’ 
before ‘return’
         return -1;

add end Line 
                              
109 -   "wl_display_add_socket_fd not supported!")
109+ "wl_display_add_socket_fd not supported!");

thank you.

**Comment by tohammer** [comment]
Thanks for reporting. This should be fixed in a current version
