### ISSUE TITLE
wiki: missing some punctuation marks

### ISSUE THREAD

**Issue by slawr** [GENIVI/ramses#24]
The wiki home page appears to missing some punctuation marks in the "Benefits" section between the benefit and its description. Maybe they are in the original source but not showing up in the rendered markdown.

Example:

> rich feature set RAMSES is a low level API, close to OpenGL

Should there be a punctuation mark between 'set' and 'RAMSES'?
> rich feature set: RAMSES is a low level API, close to OpenGL

I would have sent a correction but couldn't find any way to do it in the current setup.

**Comment by tohammer** [comment]
Thanks for the report, should be fixed now. There was a newline missing.
