### ISSUE TITLE
capu OS_WINDOWS define collides with the OS_WINDOWS define in Shlwapi.h

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/ramses#34]
Use case: ramses renderer with Spout integration

**Comment by tohammer** [comment]
Thanks for reporting!

We are currently fixing this issue. It might not be in the next release yet but should be the one after that. I will then reference it here

**Comment by tohammer** [comment]
That issue should be solved in 25.0.0 107665661dc61ae2e41c7cd51e5e7819e6d7f9d3 by removing capu dependency
