### ISSUE TITLE
Typo: basic file loading example uses sceneId 23 instead of 123

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/ramses#35]
` ramses::Scene* scene = ramses.createScene(23u, ramses::SceneConfig(), "basic scene loading from file");`

**Comment by tohammer** [comment]
That should (hopefully) not be an issue but for consistency you are right. Is already fixed internally and will be in one of the next releases

**Comment by tohammer** [comment]
Fixed with https://github.com/GENIVI/ramses/commit/0283230a5aa91ba336d279490a562554abcc6a3f
