### ISSUE TITLE
Protocol Version changes often and its history has big gaps

### ISSUE THREAD

**Issue by ManuelKugelmann** [GENIVI/ramses#38]
Right now RAMSES_TRANSPORT_PROTOCOL_VERSION_MAJOR  is at 101, the one before was 93, so that is 8 versions missing. 
Thus most of the time, the software I have to interface is using an incompatible protocol version and I have to rely on getting the matching proprietary SDK version and build against that. That's probably not the intent behind the GENIVI repositories ...
And: are there really that many breaking protocol changes on the master branch? Maybe the number of could be kept down by not incrementing it on every change happening on a dev branch?
Or maybe separate different parts of the protocol - i.e. DCSM could probably separated from vanilla display management?

**Comment by tohammer** [comment]
That should be solved with newer releases (from 24.0.1 on) where we guarantee protocol compatibility between major versions.
The big gaps in the protocol version do not indicate missed versions, but changes to the protocol during development of the next release.

**Comment by ManuelKugelmann** [comment]
@tohammer More than once, I had to request the matching in-house version of the SDK because there was no public release with a matching protocol version. Maybe non-public versions should be prohibited from use in any projects other than ramses development itself?

**Comment by tohammer** [comment]
I am not sure if we can guarantee this but with latest change that we release real versions there should always be an oss release for every major version that is compatible (file, network, api) with all internal releases of the same major version.
Would that be enough or do you really need exactly the same version?

**Comment by ManuelKugelmann** [comment]
Ususally protocol version compatibility is good enough.

**Comment by tohammer** [comment]
Great, if a specific version is missing feel free to open an issue and we can see what's possible.
