### ISSUE TITLE
Building Demo App in Android studio

### ISSUE THREAD

**Issue by Gopika1996** [GENIVI/ramses#39]
Hi,
Could you please explain the master branch have android platform support ?
And please elaborate the readme file demo/android path to include build steps in android studio?

**Comment by bkisslinger** [comment]
Hi,
yes the master branch has android platform support. You can build Ramses for Android and then either use it directly from C++ native code or write a JNI interface to use it from Java/Kotlin code. The demo in demo/android shows a simple example for a JNI interface for a Ramses Renderer.
For building it just open the Android Studio project in demo/android/ramses-renderer-android-app and run the build, there should be no extra setup required. Or do you have specific issues?

**Comment by tohammer** [comment]
Closing because no update. Feel free to open another issue when you are still experiencing problems.
