### ISSUE TITLE
Access to createEffect error messages

### ISSUE THREAD

**Issue by martin-hackenberg-paradoxcat** [GENIVI/ramses#42]
In our client application we use the following snippet to validate and if necessary to access the error messages before creating an Effect:
```
ramses_internal::String effectName(name);
ramses_internal::GlslEffect effectBlock(effectDesc.getVertexShader(), effectDesc.getFragmentShader(), effectDesc.impl.getCompilerDefines(), effectDesc.impl.getSemanticsMap(), effectName);
ramses_internal::EffectResource* effectResource = effectBlock.createEffectResource(ramses_internal::ResourceCacheFlag(cacheFlag.getValue()));
if (!effectResource) {
	outErrorMessage = std::string(effectBlock.getEffectErrorMessages().c_str());
	return false;
}
```
This is equivalent to how RamsesClientImpl::createEffect checks and logs for errors. The use of ramses_internal isn't optimal. We would require a way, via the public API, to either access the specific error messages which caused ::createEffect to fail or more preferably a validation function to retrieve errors before creation. Is there already a way to achieve this without the use of ramses_internal?

**Comment by violinyanev** [comment]
Hello @martin-hackenberg-paradoxcat ! I think what you need is already there, see:
RamsesClient::getLastEffectErrorMessages()

**Comment by violinyanev** [comment]
If it works for you, please close the issue. If not, please provide further info what's missing. Thanks!

**Comment by martin-hackenberg-paradoxcat** [comment]
Works, thanks!
