### ISSUE TITLE
Creating ramses display inside existing window under linux

### ISSUE THREAD

**Issue by martin-hackenberg-paradoxcat** [GENIVI/ramses#44]
How Is it possible to create a ramses display which renderes to an existing window under linux?

For Windows the DisplayConfig provides a configuration setting:
DisplayConfig#setWindowsWindowHandle(HWND)

**Comment by tohammer** [comment]
Unfortunately, there is currently no way to provide a handle to an existing window on linux (x11).

**Comment by tohammer** [comment]
We have it tracked now internally to add this feature. I will update this issue when we push a version that includes it.

**Comment by tohammer** [comment]
The API is now finally available since 27.0.101. More info in the API docs:
https://github.com/GENIVI/ramses/blob/master/renderer/RendererLib/ramses-renderer-api/include/ramses-renderer-api/DisplayConfig.h#L305
